# Fictional Army - Filtering and Sorting

### Introduction:

This exercise was inspired by this [page](http://chrisalbon.com/python/)

Special thanks to: https://github.com/chrisalbon for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. This is the data given as a dictionary

In [2]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Create a dataframe and assign it to a variable called army.

#### Don't forget to include the columns names in the order presented in the dictionary ('regiment', 'company', 'deaths'...) so that the column index order is consistent with the solutions. If omitted, pandas will order the columns alphabetically.

In [3]:
army = pd.DataFrame(raw_data, columns=['regiment', 'company', 'deaths', 'battles', 'size', 'veterans', 'readiness', 'armored', 'deserters', 'origin'])
display(army.head())

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine

### Step 4. Set the 'origin' colum as the index of the dataframe

In [4]:
army.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   regiment   12 non-null     object
 1   company    12 non-null     object
 2   deaths     12 non-null     int64
 3   battles    12 non-null     int64
 4   size       12 non-null     int64
 5   veterans   12 non-null     int64
 6   readiness  12 non-null     int64
 7   armored    12 non-null     int64
 8   deserters  12 non-null     int64
 9   origin     12 non-null     object
dtypes: int64(7), object(3)
memory usage: 1.1+ KB

### Step 5. Print only the column veterans

In [5]:
display(army['veterans'])

0       1
1       5
2      62
3      26
4      73
5      37
6     949
7      48
8      48
9     435
10     63
11    345
Name: veterans, dtype: int64

### Step 6. Print the columns 'veterans' and 'deaths'

In [6]:
display(army[['veterans', 'deaths']])

    veterans  deaths
0          1     523
1          5      52
2         62      25
3         26     616
4         73      43
5         37     234
6        949     523
7         48      62
8         48      62
9        435      73
10        63      37
11       345      35

### Step 7. Print the name of all the columns.

In [7]:
display(army.columns)

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters', 'origin'],
      dtype='object')

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [8]:
display(army.loc[army['origin'].isin(['Maine', 'Alaska']), ['deaths', 'size', 'deserters']])

   deaths  size  deserters
4      43  1592          3
6     523   987         24

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

In [9]:
display(army.iloc[3:8, 3:7])

   battles  size  veterans  readiness
3        2  1400        26          3
4        4  1592        73          2
5        7  1006        37          1
6        8   987       949          2
7        3   849        48          3

### Step 10. Select every row after the fourth row and all columns

In [10]:
display(army.iloc[4:, :])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 11. Select every row up to the 4th row and all columns

In [11]:
display(army.iloc[:4, :])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida

### Step 12. Select the 3rd column up to the 7th column

In [12]:
display(army.iloc[:, 2:7])

    deaths  battles  size  veterans  readiness
0      523        5  1045         1          1
1       52       42   957         5          2
2       25        2  1099        62          3
3      616        2  1400        26          3
4       43        4  1592        73          2
5      234        7  1006        37          1
6      523        8   987       949          2
7       62        3   849        48          3
8       62        4   973        48          2
9       73        7  1005       435          1
10      37        8  1099        63          2
11      35        9  1523       345          3

### Step 13. Select rows where df.deaths is greater than 50

In [13]:
display(army[army['deaths'] > 50])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

In [15]:
display(army[(army["deaths"] > 500) | (army["deaths"] < 50)])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 15. Select all the regiments not named "Dragoons"

In [19]:
display(army[army['regiment'] != 'Dragoons'])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 16. Select the rows called Texas and Arizona

In [16]:
display(army[army['origin'].isin(['Texas', 'Arizona'])])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas

### Step 17. Select the third cell in the row named Arizona

In [17]:
display(army.loc[army['origin'] == 'Arizona', 'deaths'].iloc[0])

np.int64(523)

### Step 18. Select the third cell down in the column named deaths

In [18]:
display(army[army['deaths'] > 100])

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska