# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [9]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [10]:
data = {
    "evolution": ["Ivysaur", "Charmeleon", "Wartortle", "Metapod"],
    "hp": [45, 39, 44, 45],
    "name": ["Bulbasaur", "Charmander", "Squirtle", "Caterpie"],
    "pokedex": ["yes", "no", "yes", "no"],
    "type": ["grass", "fire", "water", "bug"]
}

### Step 3. Assign it to a variable called pokemon

In [11]:
pokemon = pd.DataFrame(data)
pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [12]:
pokemon = pokemon[["name", "type", "hp", "evolution", "pokedex"]]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [13]:
pokemon["place"] = ["Forest", "Mountain", "Lake", "Garden"]
pokemon

/tmp/ipykernel_484/622795776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pokemon["place"] = ["Forest", "Mountain", "Lake", "Garden"]

         name   type  hp   evolution pokedex     place
0   Bulbasaur  grass  45     Ivysaur     yes    Forest
1  Charmander   fire  39  Charmeleon      no  Mountain
2    Squirtle  water  44   Wartortle     yes      Lake
3    Caterpie    bug  45     Metapod      no    Garden

### Step 6. Present the type of each column

In [14]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
pokedex      object
place        object
dtype: object

### BONUS: Create your own question and answer it.

In [15]:
pokemon["name"]

0     Bulbasaur
1    Charmander
2      Squirtle
3      Caterpie
Name: name, dtype: object