# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
display(chipo.head())

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [5]:
# Clean the item_price column to remove '$' and convert to float (already done in previous run, but keeping for idempotency)
# chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

# Filter the original DataFrame for items costing more than $10.00
items_over_10_df = chipo[chipo['item_price'] > 10.
unique_items_over_10 = items_over_10_df['item_name'].nunique()

print(f"Number of unique products costing more than $10.00: {unique_items_over_10}")

Number of unique products costing more than $10.00: 31

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [4]:

item_and_price = chipo[['item_name', 'item_price']]
unique_item_and_price = item_and_price.drop_duplicates()
unique_item_and_price = unique_item_and_price.sort_values(by='item_name')
display(unique_item_and_price)

              item_name  item_price
3389  6 Pack Soft Drink       12.98
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
3195      Barbacoa Bowl        8.69
95        Barbacoa Bowl        9.25
...                 ...         ...
186   Veggie Salad Bowl       11.25
3889  Veggie Soft Tacos       16.98
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [6]:

display(unique_item_and_price)

              item_name  item_price
3389  6 Pack Soft Drink       12.98
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
3195      Barbacoa Bowl        8.69
95        Barbacoa Bowl        9.25
...                 ...         ...
186   Veggie Salad Bowl       11.25
3889  Veggie Soft Tacos       16.98
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49

[209 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [7]:

max_price = chipo['item_price'].max()


most_expensive_items = chipo[chipo['item_price'] == max_price]


total_quantity_most_expensive = most_expensive_items['quantity'].sum()

print(f"The quantity of the most expensive item(s) ordered is: {total_quantity_most_expensive}")

The quantity of the most expensive item(s) ordered is: 15

veggie_salad_bowl_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]
print(f"'Veggie Salad Bowl' was ordered {veggie_salad_bowl_orders} times.")

In [8]:

veggie_salad_bowl_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]
print(f"'Veggie Salad Bowl' was ordered {veggie_salad_bowl_orders} times.")

'Veggie Salad Bowl' was ordered 18 times.

In [10]:

print(f"Data type of 'item_price': {chipo['item_price'].dtype}")

Data type of 'item_price': float64

canned_soda_multiple_orders = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]
print(f"Someone ordered more than one 'Canned Soda' {canned_soda_multiple_orders} times.")

In [9]:

canned_soda_multiple_orders = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]
print(f"Someone ordered more than one 'Canned Soda' {canned_soda_multiple_orders} times.")

Someone ordered more than one 'Canned Soda' 20 times.